name: Post welcome comment
on:
  push
permissions:
  pull-requests: write
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome to the repository!"
